import {
  Activity,
  Baby,
  Banknote,
  BatteryCharging,
  Beer,
  Bike,
  BookOpen,
  Bus,
  CakeSlice,
  Camera,
  CarFront,
  Cat,
  Clapperboard,
  Coffee,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  Flame,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Lightbulb,
  Medal,
  Music,
  Package,
  Palette,
  PartyPopper,
  Pill,
  Pizza,
  Plane,
  Plug,
  Printer,
  ReceiptText,
  Scissors,
  Shirt,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SprayCan,
  Stethoscope,
  Syringe,
  Tag,
  Ticket,
  TrainFront,
  Trophy,
  Tv,
  UtensilsCrossed,
  Watch,
  Wifi,
  Wine,
  Wrench,
} from 'lucide-react'

/**
 * Monochrome category glyphs (Fitness-style). The `icon` field of a category
 * holds either one of these keys or a legacy emoji — rendering falls back to
 * the emoji when the key is unknown, so old data and backups keep working.
 */
export const GLYPHS = {
  'shopping-cart': ShoppingCart,
  'shopping-basket': ShoppingBasket,
  utensils: UtensilsCrossed,
  pizza: Pizza,
  coffee: Coffee,
  beer: Beer,
  wine: Wine,
  cake: CakeSlice,
  bus: Bus,
  car: CarFront,
  bike: Bike,
  plane: Plane,
  train: TrainFront,
  fuel: Fuel,
  ship: Ship,
  ticket: Ticket,
  house: House,
  lightbulb: Lightbulb,
  droplets: Droplets,
  flame: Flame,
  wifi: Wifi,
  wrench: Wrench,
  receipt: ReceiptText,
  package: Package,
  pill: Pill,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  syringe: Syringe,
  dumbbell: Dumbbell,
  medal: Medal,
  trophy: Trophy,
  activity: Activity,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  scissors: Scissors,
  'spray-can': SprayCan,
  sparkles: Sparkles,
  gift: Gift,
  gamepad: Gamepad2,
  clapperboard: Clapperboard,
  music: Music,
  book: BookOpen,
  'graduation-cap': GraduationCap,
  palette: Palette,
  'party-popper': PartyPopper,
  smartphone: Smartphone,
  laptop: Laptop,
  headphones: Headphones,
  tv: Tv,
  camera: Camera,
  printer: Printer,
  battery: BatteryCharging,
  plug: Plug,
  dog: Dog,
  cat: Cat,
  tag: Tag,
  baby: Baby,
  heart: Heart,
  banknote: Banknote,
  'credit-card': CreditCard,
  landmark: Landmark,
} as const

export type GlyphKey = keyof typeof GLYPHS

export const GLYPH_KEYS = Object.keys(GLYPHS) as GlyphKey[]
